<#  Service Types Table Generator
    -----------------------------
    - Executed automatically via CI/CD (\.github\workflows\update-service-types.yml) every time JSON schema (\schema\sevice-types.json) changes
    - Loads the categories from JSON schema
    - Builds the supported service types matrix, excluding the unsupported codes in \schema\unsupported-service-types.json
    - Builds dynamic category sections (headers + tables) from JSON
    - Injects the generated content into the Markdown file (\docs\service-types.md), between markers:

        <!-- AUTOGENERATED: START -->
        <!-- AUTOGENERATED: END -->

    - Every script run replaces the block inside the markers
#>

# Paths
$root         = $PSScriptRoot
$jsonFilePath = Join-Path $root "../schema/service-types.json"
$mdFilePath   = Join-Path $root "../docs/service-types.md"

# Unsupported service types
$unsupportedPath = Join-Path $root "../schema/unsupported.json"
$unsupportedJson = Get-Content $unsupportedPath -Raw | ConvertFrom-Json
$unsupported = $unsupportedJson.unsupported

# Load JSON
$json = Get-Content $jsonFilePath | ConvertFrom-Json

$deliveryTypes = $json.delivery_type
$slotTypes     = $json.time_slot_type
$slotLengths   = $json.slot_length
$models        = $json.warehouse_models

# Timestamp for markers
$timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm")

$tableHeader = @"
| Code | Description | 
|------|-------------|
"@

$mdHeaders = @()
$categorySections = ""
$i = 0

foreach ($category in $json.PSObject.Properties) {
    $key = $category.Name                   # e.g. "slot_length"
    $spaces = $key -replace "_", " "      # e.g. "slot length"
    $header = (Get-Culture).TextInfo.ToTitleCase($spaces)
    $mdHeaders += $header                   # e.g. "Slot length"
    $header = "## " + $mdHeaders[$i] + "`n" # e.g. "## Slot length"
    
    $section = @"
$header
$tableHeader
"@ + "`n"

    foreach ($itemKey in $category.Value.PSObject.Properties.Name) {
        $section += "|$itemKey| $($category.Value.$itemKey) |`n"
    }

    $categorySections += "`n$section`n"
    $i++
}

# --- Combination Table ---
$tableHeader = @"
| Code | Description | Model |
|------|-------------|-------|
"@

$mainTable = @"
## List of Service types

$tableHeader
"@ + "`n"

foreach ($dKey in $deliveryTypes.PSObject.Properties.Name) {
    foreach ($tKey in $slotTypes.PSObject.Properties.Name) {
        foreach ($sKey in $slotLengths.PSObject.Properties.Name) {

            $serviceCode = "$dKey" + "$tKey" + "$sKey"
            
            #Combinations not supported
            if ($unsupported -contains $serviceCode) {
                $serviceCode = ""
            }

            $description = "$($deliveryTypes.$dKey) - $($slotTypes.$tKey) - $($slotLengths.$sKey)"

            # Model logic
            switch ($dKey) {
                "S" { $model = $models.both }   # WH and SFS
                "X" { $model = $models.SFS }    # SFS only
                default { $model = $models.WH } # WH only
            }
            $mainTable +=   if ($serviceCode -eq ""){ 
                                continue 
                            } else {
                                "| $serviceCode | $description | $model |`n"
                            }
            $lines++
        }
    }
}

# --- Wrap markers, categories and service types table in a single block ---
$wrappedTable = @"
<!-- Auto generated from $(Resolve-Path -Path $jsonFilePath -Relative) on: $timestamp -->
$categorySections
$mainTable
"@

# --- Inject into Markdown file ---

$mdFile = Get-Content $mdFilePath -Raw
$marker = "DYNAMIC CONTENT - DO NOT EDIT:"
$start  = "<!-- $marker START -->"
$end    = "<!-- $marker END -->"

# Regex to replace the block on the placeholder marker

if (-not ($mdFile -match [regex]::Escape($start)) -or -not ($mdFile -match [regex]::Escape($end))) {
    Write-Warning "Both anchors must be present in Markdown file:`n$start`n$end"
    exit 1
}

$pattern = "$([regex]::Escape($start)).*?$([regex]::Escape($end))"

$replacement = @"
$start
$wrappedTable
$end
"@

$updatedBlock = [regex]::Replace($mdFile, $pattern, $replacement, "Singleline")

# Write back to file
Set-Content -Path $mdFilePath -Value $updatedBlock
